Pul request 1
WilfriedDeluche/eventmaker-website pull request #1
Opened 2018-07-19 07:20 UTC by laurent-d

Hello Wilfried,

Première pull request, sachant qu'il reste une partie optimisation des JS ainsi que les templates cas clients et les mentions légales à remplir en FR et EN.

2018-07-24 12:41 UTC, WilfriedDeluche requested changes
Salut @laurent-d.
Merci pour cette très longue PR.
Je t'ai fait une quinzaine de retours, globalement sur la forme. Pas grand chose de grave.
Mais aussi quelques interrogations.

Je suis très pointilleux sur l'indentation, tu remarqueras LOL

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_annexe_en.liquid
> +    {{ 'template-custom.js' | javascript_tag }}
Tu devrais appeler `template-custom.min.js` dans les layouts désormais.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_annexe_en.liquid
> +    {% comment %}{{ 'tools.js' | javascript_tag }}{% endcomment %}
Tu peux supprimer ce commentaire, on n'aura jamais besoin de cet asset a priori.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/assets/css/style.css
> +/*
Tu ne stockes pas la version minifié de ce fichier ? On pourrait ensuite l'appeler dans les layouts.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_home_fr.liquid
> +    {% comment %}{{ 'plugins.light.js' | javascript_tag }}{% endcomment %}
Si tu n'utilises plus ce fichier dans aucun layout, autant le supprimer.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_home_fr.liquid
>      {% comment %}{{ 'tools.js' | javascript_tag }}{% endcomment %}
A retirer

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/assets/js/template-custom.js
> +event.preventDefault();
Est-ce que tu peux indenter correctement à partir d'ici jusqu'à la fin du fichier ? :)

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/assets/js/template-custom.js
> +    $(function () {
Je sais que c'était déjà comme ça avant, mais je pense que le `$(function())` est inutile pour ce bloc étant donné qu'on se trouve déjà dans un bloc `$(function())`.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_annexe_en.liquid
> +    <meta  name="og:titleog:title"  content="{% if page.seo_title != "" %}<title>{{ page.seo_title }}</title>{% else %}<title>{{ event.name }}</title>{% endif %}"/>
Est-ce normal décrire pour `og:title` 2 fois à la suite ? De même pour `og:type` et `og:url` ?
De plus, pourquoi insérer la balise `<title>` dans la valeur de `content` ? Le titre ne suffirait-il pas ?

Exemple de rendu `<meta name="og:titleog:title" content="<title>Evolution SEO - Eventmaker website</title>">`

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_annexe_en.liquid
> +    <meta name="twitter:title" content="{% if page.seo_title != "" %}<title>{{ page.seo_title }}</title>{% else %}<title>{{ event.name }}</title>{% endif %}">
Même question pour la balise HTML `<title>` qui me semble superflue.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_annexe_en.liquid
> +        <div class="row col-md-12 sub-footer">
Petit pbm d'indentation dans cette `<div>`

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/pages/en/event-id.liquid
> +{% assign sorted_articles_service = collections.services | sort: 'rank' %}
Tu peux supprimer les lignes 14 à 23 a priori.
La variable `sorted_articles_service` n'est jamais utilisée.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/pages/en/services.liquid
> +{% assign sorted_articles_service = collections.services | sort: 'rank' %}
Idem

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/pages/fr/event-id.liquid
> +{% assign sorted_articles_service = collections.services | sort: 'rank' %}
Idem

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_home_fr.liquid
>      <!--<script>
Tu peux retirer toutes les occurrences du widget Intercom de tous les layouts. On ne va plus l'utiliser de cette manière a priori.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/layout/layout_home_fr.liquid
>        var $zoho=$zoho || {};$zoho.salesiq = $zoho.salesiq || {widgetcode:"af5efb8344f61f062f0fad793b35b9d7626c571ba5486de1688cc5e0e9b595b1", values:{},ready:function(){$zoho.salesiq.floatbutton.visib
D'après Tristan, on peut également retirer toutes les occurrences de Zoho Salesiq de tous les layouts.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/pages/en/cas-client.liquid
> +      <div class="divimage dzsparallaxer--target " style="width: 101%; height: 600px; background-image: url('{{background_banner}}')"></div>
Réindenter jusqu'à la ligne 12.

2018-07-24 12:41 UTC, WilfriedDeluche commented on site/pages/en/cas-client.liquid
> +    <!-- <div class="container"> -->
A retirer.

2018-07-24 19:26 UTC, laurent-d commented on site/layout/layout_annexe_en.liquid
> +    <meta name="twitter:title" content="{% if page.seo_title != "" %}<title>{{ page.seo_title }}</title>{% else %}<title>{{ event.name }}</title>{% endif %}">
En fait nous avons besoins de spécifier les title og et twitter pour que cela soit parfaitement traité par Face & Twitter, je creuse le sujet et reviens vers toi cf https://css-tricks.com/essential-meta-tags-social-media/

2018-07-24 19:28 UTC, laurent-d commented on site/assets/css/style.css
> +/*
Pour cette première PR j'avais des doutes sur les soucis avec les prix ceci explique cela :p

2018-07-24 19:29 UTC, laurent-d commented on site/assets/js/template-custom.js
> +event.preventDefault();
Done

2018-07-24 19:29 UTC, laurent-d commented on site/assets/js/template-custom.js
> +    $(function () {
Done

2018-07-24 19:29 UTC, laurent-d commented on site/pages/en/event-id.liquid
> +{% assign sorted_articles_service = collections.services | sort: 'rank' %}
Done

2018-07-24 19:34 UTC, laurent-d commented on site/layout/layout_home_fr.liquid
>      <!--<script>
Question tu parles bien de ce script :

    <script src="https://applidget.github.io/vx-assets/orgs/applidget/eventmaker/voxevent/js/main.js"></script> 
 
?
on garde bien : 

    <script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/sc88gz64';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()
    </script>

?

2018-07-24 19:34 UTC, laurent-d commented on site/pages/fr/event-id.liquid
> +{% assign sorted_articles_service = collections.services | sort: 'rank' %}
Done

2018-07-24 19:35 UTC, laurent-d commented on site/layout/layout_home_fr.liquid
>      {% comment %}{{ 'tools.js' | javascript_tag }}{% endcomment %}
Done

2018-07-24 19:35 UTC, laurent-d commented on site/layout/layout_home_fr.liquid
> +    {% comment %}{{ 'plugins.light.js' | javascript_tag }}{% endcomment %}
C'est en cours, je veux vérifier que la version light ne créé pas d'effet de bords

2018-07-24 19:35 UTC, laurent-d commented on site/layout/layout_annexe_en.liquid
> +    {% comment %}{{ 'tools.js' | javascript_tag }}{% endcomment %}
Done

2018-07-24 19:36 UTC, laurent-d commented on site/layout/layout_annexe_en.liquid
> +    {{ 'template-custom.js' | javascript_tag }}
En cours :D

2018-07-25 13:51 UTC, WilfriedDeluche commented on site/layout/layout_home_fr.liquid
>      <!--<script>
Non justement on supprime le second, et on garde le 1er.
Le second est relatif à l'intégration du widget intercom qu'on ne veut plus.

2018-07-25 14:00 UTC, WilfriedDeluche commented on site/layout/layout_home_fr.liquid
>      <!--<script>
En fait, je ne suis pas sûr que le 1er soit non plus utile.
D'après le code, ça permet de gérer le changement de langue via un système de drapeaux. Mais ça n'existe pas sur le site...

2018-07-25 14:35 UTC, WilfriedDeluche approved these changes

2018-07-25 14:35 UTC, merged